#!/usr/bin/env python3
"""
Generate Neo4j RANGE index queries from SHOW INDEXES CSV output.

Usage:
    python3 generate_range_indexes.py input.csv -o output.cypher
"""
from __future__ import annotations

import argparse
import csv
import sys
from datetime import datetime


def parse_array_column(value: str) -> list[str]:
    """Parse '[prop1, prop2]' format to list of strings."""
    if not value:
        return []
    # Remove brackets and split by comma
    cleaned = value.strip().strip('[]')
    if not cleaned:
        return []
    return [item.strip() for item in cleaned.split(',')]


def generate_range_index_query(label: str, property_name: str) -> str:
    """Generate a single-property CREATE RANGE INDEX statement."""
    index_name = f"range_idx_{label}_{property_name}"
    return f"CREATE RANGE INDEX {index_name} FOR (n:{label}) ON (n.{property_name});"


def find_column(headers: list[str], possible_names: list[str]) -> str | None:
    """Find column name from a list of possible variations."""
    headers_lower = {h.lower().strip(): h for h in headers}
    for name in possible_names:
        if name.lower() in headers_lower:
            return headers_lower[name.lower()]
    return None


def process_csv(input_path: str) -> list[str]:
    """Read CSV, filter NODE indexes, split properties, deduplicate, generate queries."""
    seen_combinations = set()
    queries = []

    with open(input_path, 'r', newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        headers = reader.fieldnames or []

        # Find column names (handle variations)
        entity_col = find_column(headers, ['entityType', 'entitytype', 'entity_type'])
        labels_col = find_column(headers, ['labelsOrTypes', 'labelsortypes', 'labels_or_types'])
        props_col = find_column(headers, ['properties', 'property'])
        type_col = find_column(headers, ['type'])

        if not entity_col or not labels_col or not props_col or not type_col:
            print(f"Error: Required columns not found. Found columns: {headers}", file=sys.stderr)
            print(f"  entityType column: {entity_col}", file=sys.stderr)
            print(f"  labelsOrTypes column: {labels_col}", file=sys.stderr)
            print(f"  properties column: {props_col}", file=sys.stderr)
            print(f"  type column: {type_col}", file=sys.stderr)
            sys.exit(1)

        for row in reader:
            # Filter: only NODE indexes
            entity_type = row.get(entity_col, '').strip()
            if entity_type.upper() != 'NODE':
                continue

            # Filter: only BTREE indexes (skip FULLTEXT, LOOKUP, POINT, etc.)
            index_type = row.get(type_col, '').strip()
            if index_type.upper() != 'BTREE':
                continue

            # Parse labels and properties
            labels = parse_array_column(row.get(labels_col, ''))
            properties = parse_array_column(row.get(props_col, ''))

            # Generate one index per label+property combination
            for label in labels:
                for prop in properties:
                    combination = (label, prop)
                    if combination not in seen_combinations:
                        seen_combinations.add(combination)
                        queries.append(generate_range_index_query(label, prop))

    return queries


def main():
    parser = argparse.ArgumentParser(
        description='Generate Neo4j RANGE index queries from SHOW INDEXES CSV output.'
    )
    parser.add_argument('input', help='Input CSV file path')
    parser.add_argument(
        '-o', '--output',
        default='range_indexes.cypher',
        help='Output file path (default: range_indexes.cypher)'
    )

    args = parser.parse_args()

    # Process CSV and generate queries
    queries = process_csv(args.input)

    if not queries:
        print("No NODE indexes found in the input file.", file=sys.stderr)
        sys.exit(1)

    # Write output
    with open(args.output, 'w', encoding='utf-8') as outfile:
        outfile.write(f"// Generated by generate_range_indexes.py on {datetime.now().isoformat()}\n")
        outfile.write(f"// Total indexes: {len(queries)}\n\n")
        for query in queries:
            outfile.write(query + '\n')

    print(f"Generated {len(queries)} RANGE index queries to {args.output}")


if __name__ == '__main__':
    main()
